SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * ((100 - D.DISCOUNT_RATE) / 100), 0) AS FEE
# SELECT *
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ('SUV', '세단')
    AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01' 
                        AND DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-11-30')
    AND D.DURATION_TYPE = '30일 이상'
    AND C.DAILY_FEE * 30 * ((100 - D.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;

# SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100, 0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR C
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
# ON C.CAR_TYPE = P.CAR_TYPE
# WHERE C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01')
# AND C.CAR_TYPE IN ('SUV', '세단') AND P.DURATION_TYPE = '30일 이상'
# AND ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100, 0) BETWEEN 500000 AND 2000000
# ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC
