SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS b INNER JOIN USED_GOODS_USER AS u
ON b.WRITER_ID = u.USER_ID
WHERE STATUS = 'DONE'
GROUP BY b.WRITER_ID
HAVING SUM(b.PRICE) >= 700000
ORDER BY SUM(b.PRICE) ASC;